-- customer acquisition trends and inventory risks.
-- q1. show all customers from bengaluru.
select * from customers
where city='bengaluru';

-- q2. show customers who signed up after ‘2025-01-01’.
select * from customers
where signup_date>'2025-01-01';

-- q3. find customers from mumbai and hyderabad.
select * from customers
where city in ('mumbai', 'hyderabad');

-- q4. show products belonging to the electronics category.
select * from products
where category='electronics';

-- q5. find products priced above 40000.
select * from products
where price>40000;

-- q6. show products where stock is less than 20.
select * from products
where stock<20;

-- q7. find products with stock between 50 and 100.
select * from products
where stock between 50 and 100;

-- q8. show customers whose names start with ‘a’.
select * from customers
where customer_name like 'a%';

-- q9. find products whose names contain ‘premium’.
select * from products
where product_name like '%premium%';

-- q10. show customers registered during the year 2025.
select * from customers
where extract(year from signup_date)=2025;


-- part 2: revenue & sales analysis
-- business requirement: the finance department wants summarized revenue and sales insights.
-- q11. find total revenue generated by each category.
select p.category, sum(oi.quantity * oi.unit_price) as total_revenue
from order_items oi
join products p on oi.product_id = p.product_id
group by p.category;

-- q12. find total quantity sold for each product.
select p.product_name, sum(oi.quantity) as total_quantity
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name;

-- q13. find total orders under each order status.
select status, count(*) as total_orders
from orders
group by status;

-- q14. find total revenue generated through each payment method.
select o.payment_method, sum(oi.quantity * oi.unit_price) as revenue
from order_items oi
join orders o on oi.order_id = o.order_id
group by o.payment_method;

-- q15. find average product price category-wise.
select category, avg(price) as avg_price
from products
group by category;

-- q16. find category-wise quantity sold.
select p.category, sum(oi.quantity) as total_quantity
from order_items oi
join products p on oi.product_id = p.product_id
group by p.category;

-- q17. find monthly order count.
select date_format(order_date, '%y-%m') as month,
       count(*) as total_orders
from orders
group by month
order by month;

-- q18. find monthly revenue trend.
select date_format(o.order_date, '%y-%m') as month,
       sum(oi.quantity * oi.unit_price) as revenue
from orders o
join order_items oi on o.order_id = oi.order_id
group by month
order by month;

-- q19. find the most commonly used payment method.
select payment_method
from orders
group by payment_method
order by count(*) desc
limit 1;

-- q20. find the highest revenue-generating category.
select p.category
from order_items oi
join products p on oi.product_id = p.product_id
group by p.category
order by sum(oi.quantity * oi.unit_price) desc
limit 1;

-- q21. find customers who placed more than 5 orders.
select customer_id, count(*) as order_count
from orders
group by customer_id
having count(*) > 5;

-- q22. find top 5 customers based on total spending.
select o.customer_id,
       sum(oi.quantity * oi.unit_price) as total_spent
from orders o
join order_items oi on o.order_id = oi.order_id
group by o.customer_id
order by total_spent desc
limit 5;

-- q23. find products sold more than 30 times.
select p.product_name, sum(oi.quantity) as total_sold
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name
having sum(oi.quantity) > 30;

-- q24. find categories generating revenue greater than 500000.
select p.category,
       sum(oi.quantity * oi.unit_price) as revenue
from order_items oi
join products p on oi.product_id = p.product_id
group by p.category
having revenue > 500000;

-- q25. find cities having more than 10 customers.
select city, count(*) as total_customers
from customers
group by city
having count(*) > 10;

-- q26. find the top 5 highest-selling products.
select p.product_name,
       sum(oi.quantity) as total_sold
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name
order by total_sold desc
limit 5;

-- q27. find the top 3 most profitable products.
select p.product_name,
       sum(oi.quantity * oi.unit_price) as revenue
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name
order by revenue desc
limit 3;

-- q28. find customers whose spending is above average customer spending.
select customer_id, total_spent
from (
    select o.customer_id,
           sum(oi.quantity * oi.unit_price) as total_spent
    from orders o
    join order_items oi on o.order_id = oi.order_id
    group by o.customer_id
) t
where total_spent > (
    select avg(total_spent)
    from (
        select sum(oi.quantity * oi.unit_price) as total_spent
        from orders o
        join order_items oi on o.order_id = oi.order_id
        group by o.customer_id
    ) avg_table
);

-- q29. find products contributing more than 10% of company revenue.
select p.product_name,
       sum(oi.quantity * oi.unit_price) as revenue
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name
having revenue > (
    select 0.1 * sum(oi.quantity * oi.unit_price)
    from order_items oi
);

-- q30. find the city generating the highest revenue.
select c.city,
       sum(oi.quantity * oi.unit_price) as revenue
from customers c
join orders o on c.customer_id = o.customer_id
join order_items oi on o.order_id = oi.order_id
group by c.city
order by revenue desc
limit 1;