-- customer acquisition trends and inventory risks.
-- q1. show all customers from bengaluru.
select * from customers
where city='bengaluru';

-- q2. show customers who signed up after ‘2025-01-01’.
select * from customers
where signup_date>'2025-01-01';

-- q3. find customers from mumbai and hyderabad.
select * from customers
where city in ('mumbai', 'hyderabad');

-- q4. show products belonging to the electronics category.
select * from products
where category='electronics';

-- q5. find products priced above 40000.
select * from products
where price>40000;

-- q6. show products where stock is less than 20.
select * from products
where stock<20;

-- q7. find products with stock between 50 and 100.
select * from products
where stock between 50 and 100;

-- q8. show customers whose names start with ‘a’.
select * from customers
where customer_name like 'a%';

-- q9. find products whose names contain ‘premium’.
select * from products
where product_name like '%premium%';

-- q10. show customers registered during the year 2025.
select * from customers
where extract(year from signup_date)=2025;


-- part 2: revenue & sales analysis
-- business requirement: the finance department wants summarized revenue and sales insights.
-- q11. find total revenue generated by each category.
select p.category, sum(oi.quantity * oi.unit_price) as total_revenue
from order_items oi
join products p on oi.product_id = p.product_id
group by p.category;

-- q12. find total quantity sold for each product.
select p.product_name, sum(oi.quantity) as total_quantity
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name;

-- q13. find total orders under each order status.
select status, count(*) as total_orders
from orders
group by status;

-- q14. find total revenue generated through each payment method.
select o.payment_method, sum(oi.quantity * oi.unit_price) as revenue
from order_items oi
join orders o on oi.order_id = o.order_id
group by o.payment_method;

-- q15. find average product price category-wise.
select category, avg(price) as avg_price
from products
group by category;

-- q16. find category-wise quantity sold.
select p.category, sum(oi.quantity) as total_quantity
from order_items oi
join products p on oi.product_id = p.product_id
group by p.category;

-- q17. find monthly order count.
select date_format(order_date, '%y-%m') as month,
       count(*) as total_orders
from orders
group by month
order by month;

-- q18. find monthly revenue trend.
select date_format(o.order_date, '%y-%m') as month,
       sum(oi.quantity * oi.unit_price) as revenue
from orders o
join order_items oi on o.order_id = oi.order_id
group by month
order by month;

-- q19. find the most commonly used payment method.
select payment_method
from orders
group by payment_method
order by count(*) desc
limit 1;

-- q20. find the highest revenue-generating category.
select p.category
from order_items oi
join products p on oi.product_id = p.product_id
group by p.category
order by sum(oi.quantity * oi.unit_price) desc
limit 1;

-- q21. find customers who placed more than 5 orders.
select customer_id, count(*) as order_count
from orders
group by customer_id
having count(*) > 5;

-- q22. find top 5 customers based on total spending.
select o.customer_id,
       sum(oi.quantity * oi.unit_price) as total_spent
from orders o
join order_items oi on o.order_id = oi.order_id
group by o.customer_id
order by total_spent desc
limit 5;

-- q23. find products sold more than 30 times.
select p.product_name, sum(oi.quantity) as total_sold
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name
having sum(oi.quantity) > 30;

-- q24. find categories generating revenue greater than 500000.
select p.category,
       sum(oi.quantity * oi.unit_price) as revenue
from order_items oi
join products p on oi.product_id = p.product_id
group by p.category
having revenue > 500000;

-- q25. find cities having more than 10 customers.
select city, count(*) as total_customers
from customers
group by city
having count(*) > 10;

-- q26. find the top 5 highest-selling products.
select p.product_name,
       sum(oi.quantity) as total_sold
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name
order by total_sold desc
limit 5;

-- q27. find the top 3 most profitable products.
select p.product_name,
       sum(oi.quantity * oi.unit_price) as revenue
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name
order by revenue desc
limit 3;

-- q28. find customers whose spending is above average customer spending.
select customer_id, total_spent
from (
    select o.customer_id,
           sum(oi.quantity * oi.unit_price) as total_spent
    from orders o
    join order_items oi on o.order_id = oi.order_id
    group by o.customer_id
) t
where total_spent > (
    select avg(total_spent)
    from (
        select sum(oi.quantity * oi.unit_price) as total_spent
        from orders o
        join order_items oi on o.order_id = oi.order_id
        group by o.customer_id
    ) avg_table
);

-- q29. find products contributing more than 10% of company revenue.
select p.product_name,
       sum(oi.quantity * oi.unit_price) as revenue
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name
having revenue > (
    select 0.1 * sum(oi.quantity * oi.unit_price)
    from order_items oi
);

-- q30. find the city generating the highest revenue.
select c.city,
       sum(oi.quantity * oi.unit_price) as revenue
from customers c
join orders o on c.customer_id = o.customer_id
join order_items oi on o.order_id = oi.order_id
group by c.city
order by revenue desc
limit 1;


-- Q31. Display all orders along with customer names.
select o.order_id , c.customer_name,o.order_date,o.status,o.payment_method from customers c
join orders o 
on c.customer_id=o.customer_id;
-- Q32. Find total revenue generated by each customer.
select c.customer_id, sum(oi.quantity*oi.unit_price) from customers c 
join orders o on c.customer_id=o.customer_id
join order_items oi on o.order_id=oi.order_id
group by c.customer_id;
-- Q33. Find the total number of orders placed by each customer.
select  c.customer_name,count(o.order_id) as total_orders  from customers c
join orders o 
on c.customer_id=o.customer_id
group by c.customer_name
order by total_orders desc;
-- Q34. Find customers who never placed any orders.
select c.customer_name from customers c
left join orders o
on c.customer_id=o.customer_id
where o.order_id is null;
-- Q35. Find the latest order date for each customer.
select c.customer_name,max(o.order_date) as last_order  from customers c
join orders o
on c.customer_id=o.customer_id
group by c.customer_name;
-- Q36. Find product-wise revenue generated.
select p.product_name, sum(oi.quantity*oi.unit_price)  as product_revenue from products p
join order_items oi
on p.product_id=oi.product_id
group by p.product_name;
-- Q37. Find products that were never sold.
select p.product_name from products p
left join order_items oi
on p.product_id=oi.product_id
where oi.product_id is null;

-- Q38. Find products whose stock is lower than the total quantity sold.
select p.product_name, sum(oi.quantity) as total_quantity,  p.stock 
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.product_name,p.stock 
having p.stock < total_quantity
order by total_quantity desc;
-- Q39. Find category-wise revenue contribution percentage.
select p.category,
       sum(oi.quantity * oi.unit_price) as category_revenue,
       sum(oi.quantity * oi.unit_price) * 100.0 / sum(sum(oi.quantity * oi.unit_price)) over() as percentage_of_total 
from products p
join order_items oi on p.product_id = oi.product_id
group by p.category;
-- Q40. Find repeat customers who ordered in multiple months.
select  c.customer_name, count(date_format(order_date,"%Y-%M"))  active_customers
from customers c
join orders o 
on c.Customer_id=o.Customer_id
group by c.customer_name
having active_customers >1
order by active_customers;

-- q41. calculate overall company revenue.
select sum(oi.quantity*oi.unit_price) as company_revenue
from order_items as oi
join orders o on o.order_id=oi.order_id
where o.status ='delivered' ;

-- q42. calculate average order value.
select sum(oi.quantity * oi.unit_price) / count(distinct o.order_id) as average_order_value
from orders o
join order_items oi on o.order_id = oi.order_id
where o.status = 'delivered';

-- q43. calculate cancelled order percentage.
select 
    sum(case when o.status = 'cancelled' 
             then oi.quantity * oi.unit_price else 0 end) * 100.0
    / sum(oi.quantity * oi.unit_price) as cancelled_revenue_percentage
from order_items oi
join orders o 
    on o.order_id = oi.order_id;

-- q44. find the month with highest revenue.
select 
    date_format(o.order_date, '%y-%m') as month,
    sum(oi.quantity * oi.unit_price) as revenue
from orders o
join order_items oi 
    on o.order_id = oi.order_id
where o.status = 'delivered'
group by month
order by revenue desc
limit 1;

-- q45. find the month with highest order volume.
select 
    date_format(order_date, '%y-%m') as month,
    count(*) as total_orders
from orders
group by month
order by total_orders desc
limit 1;

-- q46. find the most common order status.
select 
    status,
    count(*) as total_count
from orders
group by status
order by total_count desc
limit 1;

-- q47. generate a payment-method-wise revenue report.
select 
    o.payment_method,
    sum(oi.quantity * oi.unit_price) as revenue
from orders o
join order_items oi 
    on o.order_id = oi.order_id
where o.status = 'delivered'
group by o.payment_method
order by revenue desc;

-- q48. generate a category-wise business summary report.
select 
    p.category,
    count(distinct o.order_id) as total_orders,
    sum(oi.quantity) as total_quantity,
    sum(oi.quantity * oi.unit_price) as total_revenue
from products p
join order_items oi 
    on p.product_id = oi.product_id
join orders o 
    on o.order_id = oi.order_id
where o.status = 'delivered'
group by p.category
order by total_revenue desc;

-- q49. generate a city-wise customer and revenue report.
select 
    c.city,
    count(distinct c.customer_id) as total_customers,
    sum(oi.quantity * oi.unit_price) as total_revenue
from customers c
join orders o 
    on c.customer_id = o.customer_id
join order_items oi 
    on o.order_id = oi.order_id
where o.status = 'delivered'
group by c.city
order by total_revenue desc;